version: "3.1"
services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=DEBUG"
      - "--accesslog"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--providers.file.filename=/etc/ssl/traefik/tls.yml" # dynamic config

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./tls:/etc/ssl/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.traefik.me`)"
      - "traefik.http.routers.traefik-https.entrypoints=https"
      - "traefik.http.routers.traefik-https.service=traefik-https"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.services.traefik-https.loadbalancer.server.port=8080"




# keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_PORT: 9090
      KC_PROXY: edge
      KC_FEATURES: recovery-codes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=HostRegexp(`{subdomain:^keycloak(-[\\d-]+)?}.traefik.me`)"
      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.routers.keycloak.tls=true"

      #mtls config
      - "traefik.http.routers.mtls-keycloak.rule=Host(`mtls-keycloak.traefik.me`)"
      # - "traefik.http.routers.mtls-keycloak.rule=HostRegexp(`{subdomain:^mtls-keycloak(-[\\d-]+)?}.traefik.me`)"
      - "traefik.http.routers.mtls-keycloak.entrypoints=https"
      - "traefik.http.routers.mtls-keycloak.service=keycloak@docker"
      - "traefik.http.routers.mtls-keycloak.tls.options=mtls@file"
      - "traefik.http.services.keycloak.loadbalancer.server.port=9090"
    command:
    - start-dev
    - "--import-realm"
    # volumes:
    # - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - 9090:9090
