version: "3.1"
services:
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=INFO"
      - "--accesslog"
      - "--api"
      - "--api.dashboard"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./tls:/tls"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.traefik-https.service=traefik-https"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.services.traefik-https.loadbalancer.server.port=8080"
